plugins { id 'com.android.application' version '8.3.0' apply true }
android {
    namespace 'com.muxiniu.ncmtest'
    compileSdk 34
    defaultConfig { applicationId "com.muxiniu.ncmtest"; minSdk 21; targetSdk 34 }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { implementation 'androidx.core:core:1.12.0' }
